%% Read file data generated by OceanView
function [sub_wavelength, sub_intensity] = ReadTxtFiles(fileDir, filename, wavelength_range)
% open the file for reading
if filename(end-3) ~= '.'
    fullpath = fullfile(fileDir, [filename '.txt']);
else
    fullpath = fullfile(fileDir, filename);
end
fid = fopen(fullpath, 'r');

% initialize the arrays to hold the data
wavelength = [];
intensity = [];

% read each line of the file
while ~feof(fid)
    line = fgetl(fid);

    % check if there is any non-numeric data in the line
    if isnan(str2double(regexp(line, '[^\s]+', 'match')))

        % if there is, skip this line and move on to the next one
        continue;
    end

    % if all the data in the line is numeric, extract the two columns
    % and save them in the arrays
    data = str2num(line);
    if ~isempty(data)
        wavelength = [wavelength; data(1)];
        intensity = [intensity; data(2)];
    end
end

% find the indices of the elements within the range
indices = wavelength >= wavelength_range(1) & wavelength <= wavelength_range(2);

% extract the subwavelength
sub_wavelength = wavelength(indices);
sub_intensity = intensity(indices);

fclose(fid);
end